# Generated by Django 3.2.20 on 2023-08-14 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0002_auto_20230813_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.IntegerField(choices=[(1, 'Manual Work'), (2, 'Admin Work'), (3, 'Campaign Work'), (4, 'Other')], default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'Publish')], default=0),
        ),
    ]
