# Generated by Django 3.2.20 on 2023-08-17 19:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taskapp', '0003_auto_20230814_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Live')], default=0),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2)])),
                ('surname', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2)])),
                ('mobile_prefix', models.CharField(choices=[('087', '087'), ('086', '086'), ('085', '085'), ('083', '083')], max_length=3)),
                ('mobile_number', models.CharField(default='1234567', max_length=7, validators=[django.core.validators.RegexValidator(message='7 digits please', regex='^\\d{7}$')])),
                ('gate_code', models.CharField(default='1234', max_length=4)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, validators=[django.core.validators.MinLengthValidator(4)])),
            ],
        ),
    ]
