# Generated by Django 3.2.20 on 2023-08-20 23:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0006_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mobile_number',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Mobile needs 7 digits please', regex='^\\d{7}$')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile_prefix',
            field=models.CharField(choices=[('087', '087'), ('086', '086'), ('085', '085'), ('083', '083')], default='---', max_length=3),
        ),
    ]
